const t = {
  uk: {
    languageSelected: "Ви обрали Українську",
    pleaseChoose: "Будь ласка, оберіть",
    askName: " Будь ласка, вкажіть своє 👤 Ім'я та Прізвище:",
    nextButton: "Далі",
    nameSaved: "✅ Ім'я та прізвище збережено.",
    phoneSaved: "Введіть номер 📞 (9 цифр Без +38) або натисніть «Пропустити»",
    miss: "Пропустити",
    notPhone: "Ви не надали номер",
    thanks: "Дякуємо! Ваші дані збережено.",
    title: "🏠 Головне меню",
    profile: "👤 Мій профіль",
    book: "📅 Записатись",
    cancel: "❌ Скасувати запис",
    portfolio: "🖼️ Портфоліо",
    chooseService: "Оберіть будь ласка послугу",
    manicure: "💅 Манікюр",
    pedicure: "🦶 Педикюр",
    removal: "❌ Зняття",
    strengthen: "💪 Укріплення",
    mainMenu: "⬅️ Повернутись до головного меню",
    adminTitle: "🔧 Адмін-панель",
    viewAllRecords: "📋 Переглянути всі записи",
    blockDate: "📅 Заблокувати дату",
    blockHours: "⏰ Заблокувати години",
    addPortfolio: "🖼️ Додати фото до портфоліо",
  },
  pl: {
    languageSelected: "Wybrałeś język polski.",
    pleaseChoose: "Proszę wybrać",
    askName: "Proszę podać swoje 👤 Imię i Nazwisko:",
    nextButton: "Dalej",
    nameSaved: "✅ Imię i Nazwisko zostały zapisane.",
    phoneSaved: "Wprowadź numer 📞 (9 cyfr, bez +48), lub kliknij „Pomiń”:",
    miss: "Pomiń",
    notPhone: "Nie podałeś numeru.",
    thanks: "Dziękuję! Twoje dane zostały zapisane.",
    title: "🏠 Menu główne",
    profile: "👤 Mój profil",
    book: "📅 Umów się",
    cancel: "❌ Anuluj wizytę",
    portfolio: "🖼️ Portfolio",
    chooseService: "Proszę wybrać usługę",
    manicure: "💅 Manicure",
    pedicure: "🦶 Pedicure",
    removal: "❌ Usunięcie",
    strengthen: "💪 Wzmocnienie",
    mainMenu: "⬅️ Powrót do menu głównego",
    adminTitle: "🔧 Panel administratora",
    viewAllRecords: "📋 Wyświetl wszystkie zapisy",
    blockDate: "📅 Zablokuj datę",
    blockHours: "⏰ Zablokuj godziny",
    addPortfolio: "🖼️ Dodaj zdjęcie do portfolio",
  },
};

module.exports = t;
